### ISSUE TITLE
How2 crashes when pressing space while viewing a question with no answers

### ISSUE THREAD

**Issue by luigimannoni** [santinic/how2#63]
Steps to reproduce:
- Ask a question
- Press space to see more choices
- Find a question with no answers
- Press space on the empty answer list

<img width="988" alt="screen shot 2016-03-15 at 10 24 29" src="https://cloud.githubusercontent.com/assets/1405327/13774684/2c000c3a-ea98-11e5-9ebe-0d6821073476.png">

```
TypeError: Cannot read property 'body_markdown' of undefined
    at Object.showAnswer (/usr/local/lib/node_modules/how2/lib/ui.js:177:46)
    at /usr/local/lib/node_modules/how2/lib/how2.js:120:20
    at ScrollableBox.<anonymous> (/usr/local/lib/node_modules/how2/lib/ui.js:151:9)
    at ScrollableBox.EventEmitter._emit (/usr/local/lib/node_modules/how2/node_modules/blessed/lib/events.js:94:20)
    at ScrollableBox.EventEmitter.emit (/usr/local/lib/node_modules/how2/node_modules/blessed/lib/events.js:117:12)
    at ScrollableBox.List.enterSelected (/usr/local/lib/node_modules/how2/node_modules/blessed/lib/widgets/list.js:586:8)
    at ScrollableBox.<anonymous> (/usr/local/lib/node_modules/how2/lib/ui.js:155:21)
    at ScrollableBox.EventEmitter._emit (/usr/local/lib/node_modules/how2/node_modules/blessed/lib/events.js:94:20)
    at ScrollableBox.EventEmitter.emit (/usr/local/lib/node_modules/how2/node_modules/blessed/lib/events.js:117:12)
    at Program.<anonymous> (/usr/local/lib/node_modules/how2/node_modules/blessed/lib/widgets/screen.js:603:15)
```

**Comment by danyshaanan** [comment]
BTW, to reproduce the problem I used this question:
```bash
./bin/how2 docker compose create containers
```
(second question has no answers)
