### ISSUE TITLE
error after pressing space

### ISSUE THREAD

**Issue by smmoosavi** [santinic/how2#68]
every time I press space following error shown:
```
Press SPACE for more choices, any other key to quit.
TypeError: Invalid Version: null
    at new SemVer (/home/my-user/.npm-packages/lib/node_modules/how2/node_modules/semver/semver.js:279:11)
    at compare (/home/my-user/.npm-packages/lib/node_modules/how2/node_modules/semver/semver.js:566:10)
    at Function.gt (/home/my-user/.npm-packages/lib/node_modules/how2/node_modules/semver/semver.js:595:10)
    at /home/my-user/.npm-packages/lib/node_modules/how2/lib/updates.js:15:19
    at Request._callback (/home/my-user/.npm-packages/lib/node_modules/how2/node_modules/npm-latest/lib/npm-latest.js:53:5)
    at Request.self.callback (/home/my-user/.npm-packages/lib/node_modules/how2/node_modules/request/request.js:200:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/my-user/.npm-packages/lib/node_modules/how2/node_modules/request/request.js:1067:10)
    at emitOne (events.js:82:20)

```

**Comment by smmoosavi** [comment]
I found that this error occurs when I use [sinopia](https://github.com/rlidwka/sinopia/)

```
cat .npmrc
registry=http://localhost:4873/
```

**Comment by danyshaanan** [comment]
@smmoosavi - Can you compare your how2 version in both cases, and if identical, compare the versions of its dependencies when installed with and without?

**Comment by smmoosavi** [comment]
```
how2 --version
how2 version 1.1.0 - by Claudio Santini
```

**Comment by danyshaanan** [comment]
Please give exact reproduction steps so that we could test this, and include OS type and version, node version, and npm version.

**Comment by smmoosavi** [comment]
If you want to reproduce error:
```
$ npm i how2
$ npm i sinopia
$ cat ~/.npmrc  # is empty
$ ./node_modules/.bin/how2 -l python list length  
# no error until this line

$ npm set registry http://localhost:4873
$ cat ~/.npmrc
registry=http://localhost:4873

$./node_modules/.bin/sinopia
$ ./node_modules/.bin/how2 -l python list length 
# errors TypeError: Invalid Version: null ...

$ echo '' > ~/.npmrc
./node_modules/.bin/how2 -l python list length  
# every thing is ok
```

Ubuntu 14.04 LTS
npm 3.3.12
node v5.1.0

**Comment by danyshaanan** [comment]
Probably an issue with [npm-latest](https://www.npmjs.com/package/npm-latest), originating in [this line](https://github.com/santinic/how2/blob/c75c0e34c97bd2ec107f9f14b5de773030ffa0ad/lib/updates.js#L10).

Could you please run:
```bash
npm i npm-latest
echo '' > ~/.npmrc
./node_modules/.bin/npm-latest how2
echo 'registry=http://localhost:4873' > ~/.npmrc
./node_modules/.bin/sinopia
./node_modules/.bin/npm-latest how2
```
?

**Comment by smmoosavi** [comment]
yes, you are right.
with sinopia
```
  how2: 
    latest: null
    last updated: null
```
with default registry
```
  how2: 
    latest: 1.1.0
    last updated: Mon Mar 07 2016 23:53:18 GMT+0330 (IRST)
    author: Claudio Santini
    repo: https://github.com/santinic/how2
    description: Uses Google and Stackoverflow to find how to do things on a Unix commmand line
```
