### ISSUE TITLE
Error: Cannot read property 'prototype' of undefined.

### ISSUE THREAD

**Issue by TheManticore** [santinic/how2#91]
$ how2 hello world
/usr/local/lib/node_modules/how2/node_modules/devnull/transports/transport.js:59
Transport.prototype.__proto__ = EventEmitter.prototype;
                                             ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/how2/node_modules/devnull/transports/transport.js:59:46)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/how2/node_modules/devnull/transports/stream.js:8:17)
    at Module._compile (module.js:652:30)

Installed version of node.js: v8.10.0
Installed version of npm:  v3.5.2

$ npm list -g --depth=0
/usr/local/lib
├── fkill-cli@5.0.0
├── get-port-cli@1.1.0
├── how2@1.5.0
├── internal-ip-cli@1.0.0
├── opn-cli@3.1.0
├── public-ip-cli@1.1.2
└── tldr@3.2.5
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

Hope that helps. :)

**Comment by PaoloCifariello** [comment]
Hi @TheManticore, take a look at #89 and my previous comment (https://github.com/santinic/how2/issues/89#issuecomment-390953309) which should solve the problem.

**Comment by TheManticore** [comment]
Well now, it seems I need to update my deployment script. Thanks!
