### ISSUE TITLE
Query error with mongodb

### ISSUE THREAD

**Issue by albertotn** [santinic/how2#99]
Running following command:

`how2 mongodb query aggregation`

give that error:

```
/{ AssertionError [ERR_ASSERTION]: null == true
    at fetchQuestionAnswers (C:\Users\user1\AppData\Roaming\npm\node_modules\how-2\lib\how2.js:23:5)
    at onAfterSearch (C:\Users\user1\AppData\Roaming\npm\node_modules\how-2\lib\how2.js:135:29)
    at Object.main (C:\Users\user1\AppData\Roaming\npm\node_modules\how-2\lib\how2.js:183:9)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
  generatedMessage: true,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: null,
  expected: true,
  operator: '==' }
```

**Comment by ahaverty** [comment]
I'm getting a similar error with `how2 delete local merged branches`

**Comment by santinic** [comment]
Fixed
